# -*- coding: utf-8 -*-
"""cleaned_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16facKJTvDreEGJLXs8-v0CpDIyTQtxSE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries ready")

from google.colab import files

print("📂 Upload: FY_2025_Hospital_Readmissions_Reduction_Program_Hospital.csv")
uploaded = files.upload()

readm_raw = pd.read_csv(list(uploaded.keys())[0])
print(f"Raw rows (all conditions): {len(readm_raw):,}")
print("Conditions in file:", readm_raw['Measure Name'].unique())

# Filter to Heart Failure only
hf = readm_raw[readm_raw['Measure Name'] == 'READM-30-HF-HRRP'].copy()

hf = hf.rename(columns={
    'Excess Readmission Ratio':   'ERR',
    'Number of Discharges':       'hf_discharges',
    'Number of Readmissions':     'hf_readmissions',
    'Predicted Readmission Rate': 'predicted_rate',
    'Expected Readmission Rate':  'expected_rate',
})

# Clean up
hf['Facility ID']     = hf['Facility ID'].astype(str).str.zfill(6)
hf['ERR']             = pd.to_numeric(hf['ERR'], errors='coerce')
hf['hf_discharges']   = pd.to_numeric(hf['hf_discharges'], errors='coerce')
hf['hf_readmissions'] = pd.to_numeric(hf['hf_readmissions'], errors='coerce')
hf['penalized']       = (hf['ERR'] > 1.0).astype(int)

hf = hf[['Facility ID','State','ERR','hf_discharges','hf_readmissions',
          'predicted_rate','expected_rate','penalized']]

print(f"HF hospitals: {len(hf):,}")
print(f"ERR available: {hf['ERR'].notna().sum():,}")
print(f"Penalized (ERR > 1.0): {hf['penalized'].sum():,}  ({hf['penalized'].mean()*100:.1f}%)")
hf.head()

print("📂 Upload: Hospital_General_Information.csv")
uploaded = files.upload()

hosp_raw = pd.read_csv(list(uploaded.keys())[0])
hosp_raw['Facility ID'] = hosp_raw['Facility ID'].astype(str).str.zfill(6)
print(f"Loaded: {len(hosp_raw):,} hospitals")
hosp_raw.columns.tolist()

# Keep only what we need and clean it
hosp = hosp_raw[[
    'Facility ID', 'Facility Name', 'City/Town', 'State',
    'Hospital Type', 'Hospital Ownership',
    'Hospital overall rating', 'Emergency Services',
]].copy()

# Simplify ownership → 3 categories
def clean_ownership(val):
    if pd.isna(val): return 'Unknown'
    v = str(val).lower()
    if 'proprietary' in v or 'physician' in v: return 'For-Profit'
    if 'non-profit' in v or 'church' in v:     return 'Non-Profit'
    if any(k in v for k in ['government','district','federal','state','local','tribal']): return 'Government'
    return 'Other'

hosp['ownership_cat'] = hosp['Hospital Ownership'].apply(clean_ownership)

# Hospital type → 2 categories
hosp['type_cat'] = hosp['Hospital Type'].apply(
    lambda v: 'Critical Access' if 'Critical' in str(v)
    else 'Acute Care' if 'Acute' in str(v)
    else 'Other'
)

# Star rating → numeric
hosp['overall_rating'] = pd.to_numeric(
    hosp['Hospital overall rating'].replace('Not Available', np.nan),
    errors='coerce'
)

hosp['has_emergency'] = (hosp['Emergency Services'] == 'Yes').astype(int)

# Drop original raw columns now that we have clean ones
hosp.drop(columns=['Hospital Type','Hospital Ownership',
                   'Hospital overall rating','Emergency Services'], inplace=True)

print(f"Cleaned hospital info: {len(hosp):,} rows")
print("\nOwnership breakdown:")
print(hosp['ownership_cat'].value_counts())
hosp.head()

print("📂 Upload: HCAHPS-Hospital.csv")
uploaded = files.upload()

hcahps_raw = pd.read_csv(list(uploaded.keys())[0])
hcahps_raw['Facility ID'] = hcahps_raw['Facility ID'].astype(str).str.zfill(6)
print(f"Raw HCAHPS rows (long format): {len(hcahps_raw):,}")
print(f"Unique measures: {hcahps_raw['HCAHPS Measure ID'].nunique()}")

# We only want the continuous Linear Mean Score measures
HCAHPS_KEEP = {
    'H_COMP_1_LINEAR_SCORE':     'hcahps_nurse_comm',
    'H_COMP_2_LINEAR_SCORE':     'hcahps_doctor_comm',
    'H_COMP_5_LINEAR_SCORE':     'hcahps_discharge_info',
    'H_COMP_6_LINEAR_SCORE':     'hcahps_care_transition',
    'H_HSP_RATING_LINEAR_SCORE': 'hcahps_overall_rating',
    'H_RECMND_LINEAR_SCORE':     'hcahps_recommend',
}

# Filter to only those rows
hcahps_long = hcahps_raw[
    hcahps_raw['HCAHPS Measure ID'].isin(HCAHPS_KEEP.keys())
][['Facility ID','HCAHPS Measure ID','HCAHPS Linear Mean Value']].copy()

hcahps_long['HCAHPS Linear Mean Value'] = pd.to_numeric(
    hcahps_long['HCAHPS Linear Mean Value'], errors='coerce'
)

# Pivot: one row per hospital, one column per measure
hcahps = (hcahps_long
          .pivot_table(index='Facility ID',
                       columns='HCAHPS Measure ID',
                       values='HCAHPS Linear Mean Value',
                       aggfunc='mean')
          .reset_index())
hcahps.columns.name = None
hcahps.rename(columns=HCAHPS_KEEP, inplace=True)

print(f"Before pivot: {len(hcahps_long):,} rows (long)")
print(f"After pivot:  {len(hcahps):,} rows (wide — one per hospital)")
hcahps.head()

print("📂 Upload: Timely_and_Effective_Care-Hospital.csv")
uploaded = files.upload()

timely_raw = pd.read_csv(list(uploaded.keys())[0])
timely_raw['Facility ID'] = timely_raw['Facility ID'].astype(str).str.zfill(6)
print(f"Raw rows: {len(timely_raw):,}")
print(f"Unique measures: {timely_raw['Measure ID'].nunique()}")

TIMELY_KEEP = {
    'SEP_1':  'tc_sepsis_care',
    'VTE_1':  'tc_vte_prophylaxis',
    'VTE_2':  'tc_vte_discharge',
    'IMM_3':  'tc_influenza_vax',
    'OP_22':  'tc_ed_left_no_seen',
}

timely_long = timely_raw[
    timely_raw['Measure ID'].isin(TIMELY_KEEP.keys())
][['Facility ID','Measure ID','Score']].copy()

timely_long['Score'] = pd.to_numeric(
    timely_long['Score'].replace({'Not Available': np.nan, 'low': np.nan}),
    errors='coerce'
)

timely = (timely_long
          .pivot_table(index='Facility ID',
                       columns='Measure ID',
                       values='Score',
                       aggfunc='mean')
          .reset_index())
timely.columns.name = None
timely.rename(columns=TIMELY_KEEP, inplace=True)

print(f"Timely care wide: {len(timely):,} hospitals")
# Check coverage per measure
print("\nData coverage per measure:")
for col in [c for c in timely.columns if c != 'Facility ID']:
    pct = timely[col].notna().mean() * 100
    print(f"  {col}: {pct:.1f}% have data")
timely.head()

print("📂 Upload: FY_2025_HAC_Reduction_Program_Hospital.csv")
uploaded = files.upload()

hac_raw = pd.read_csv(list(uploaded.keys())[0])
hac_raw['Facility ID'] = hac_raw['Facility ID'].astype(str).str.zfill(6)
print(f"Loaded: {len(hac_raw):,} rows")
hac_raw.columns.tolist()

hac = hac_raw[[
    'Facility ID',
    'PSI 90 Composite Value',
    'Total HAC Score',
    'Payment Reduction',
]].copy()

hac.rename(columns={
    'PSI 90 Composite Value': 'hac_psi90',
    'Total HAC Score':        'hac_total_score',
    'Payment Reduction':      'hac_penalty_raw',
}, inplace=True)

hac['hac_psi90']        = pd.to_numeric(hac['hac_psi90'], errors='coerce')
hac['hac_total_score']  = pd.to_numeric(hac['hac_total_score'], errors='coerce')
hac['hac_penalty_flag'] = (hac['hac_penalty_raw'] == 'Yes').astype(int)
hac.drop(columns=['hac_penalty_raw'], inplace=True)

print(f"HAC dataset: {len(hac):,} hospitals")
print(f"Penalized (worst 25%): {hac['hac_penalty_flag'].sum():,}")
hac.head()

print("📂 Upload: Medicare_Hospital_Spending_Per_Patient-Hospital.csv")
uploaded = files.upload()

mspb_raw = pd.read_csv(list(uploaded.keys())[0])
mspb_raw['Facility ID'] = mspb_raw['Facility ID'].astype(str).str.zfill(6)

mspb = mspb_raw[['Facility ID','Score']].copy()
mspb['Score'] = pd.to_numeric(mspb['Score'], errors='coerce')
mspb.rename(columns={'Score': 'medicare_spending_ratio'}, inplace=True)

print(f"Loaded: {len(mspb):,} hospitals")
print(f"Median spending ratio: {mspb['medicare_spending_ratio'].median():.3f}")
mspb.head()

print("Merging all datasets...\n")

df = hf.copy()
print(f"Spine (HF):            {len(df):>6,} rows")

df = df.merge(hosp,   on='Facility ID', how='left')
print(f"+ Hospital Info:       {len(df):>6,} rows")

df = df.merge(hcahps, on='Facility ID', how='left')
print(f"+ HCAHPS:              {len(df):>6,} rows")

df = df.merge(timely, on='Facility ID', how='left')
print(f"+ Timely Care:         {len(df):>6,} rows")

df = df.merge(hac,    on='Facility ID', how='left')
print(f"+ HAC Safety:          {len(df):>6,} rows")

df = df.merge(mspb,   on='Facility ID', how='left')
print(f"+ Medicare Spending:   {len(df):>6,} rows")

print(f"\n✅ Final merged shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
df.head()

# Drop rows where ERR is missing (no target = can't model)
df = df.dropna(subset=['ERR']).copy()

# Fix the duplicate State column from the merge
# (hf had 'State', hosp also had 'State' → pandas renamed them State_x / State_y)
if 'State_x' in df.columns:
    df.rename(columns={'State_x': 'State'}, inplace=True)
    df.drop(columns=['State_y'], inplace=True, errors='ignore')

print(f"Rows after dropping missing ERR: {len(df):,}")

# Census region from state
REGION_MAP = {
    'CT':'Northeast','ME':'Northeast','MA':'Northeast','NH':'Northeast',
    'RI':'Northeast','VT':'Northeast','NJ':'Northeast','NY':'Northeast','PA':'Northeast',
    'IL':'Midwest','IN':'Midwest','MI':'Midwest','OH':'Midwest','WI':'Midwest',
    'IA':'Midwest','KS':'Midwest','MN':'Midwest','MO':'Midwest','NE':'Midwest',
    'ND':'Midwest','SD':'Midwest',
    'DE':'South','FL':'South','GA':'South','MD':'South','NC':'South','SC':'South',
    'VA':'South','DC':'South','WV':'South','AL':'South','KY':'South','MS':'South',
    'TN':'South','AR':'South','LA':'South','OK':'South','TX':'South',
    'AZ':'West','CO':'West','ID':'West','MT':'West','NV':'West','NM':'West',
    'UT':'West','WY':'West','AK':'West','CA':'West','HI':'West','OR':'West','WA':'West',
}
df['region'] = df['State'].map(REGION_MAP).fillna('Other')

# Dummy variables
df['is_forprofit']     = (df['ownership_cat'] == 'For-Profit').astype(int)
df['is_government']    = (df['ownership_cat'] == 'Government').astype(int)
df['region_northeast'] = (df['region'] == 'Northeast').astype(int)
df['region_south']     = (df['region'] == 'South').astype(int)
df['region_west']      = (df['region'] == 'West').astype(int)

# Log transform HF volume
df['log_hf_discharges'] = np.log1p(df['hf_discharges'])

print("Feature engineering done.")
print(f"\nRegion distribution:\n{df['region'].value_counts()}")
print(f"\nOwnership distribution:\n{df['ownership_cat'].value_counts()}")

miss = df.isnull().mean().mul(100).round(1).sort_values(ascending=False)
miss = miss[miss > 0]

print("Missing % per column:\n")
print(miss.to_string())

# Flag anything >50% — should be dropped before modeling
high_miss = miss[miss > 50].index.tolist()
print(f"\n⚠️  Columns >50% missing (drop before modeling): {high_miss}")

print("=" * 50)
print(f"Final dataset: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"ERR range:     {df['ERR'].min():.3f} – {df['ERR'].max():.3f}")
print(f"ERR mean:      {df['ERR'].mean():.3f}")
print(f"Penalized:     {df['penalized'].sum():,} ({df['penalized'].mean()*100:.1f}%)")
print("=" * 50)

df.to_csv('team7_master_dataset.csv', index=False)
print("\n✅ Saved: team7_master_dataset.csv")

# Download to your machine
from google.colab import files
files.download('team7_master_dataset.csv')

# See the full picture of missing values
miss = df.isnull().mean().mul(100).round(1).sort_values(ascending=False)
miss = miss[miss > 0]
print(miss.to_string())

# ── RULE 1: Drop columns with >50% missing (too unreliable to use) ──
cols_to_drop = miss[miss > 50].index.tolist()
print(f"Dropping {len(cols_to_drop)} columns with >50% missing:")
print(cols_to_drop)

df.drop(columns=cols_to_drop, inplace=True)

# ── RULE 2: Median impute numeric columns with <50% missing ─────────
# Median is safer than mean — not affected by outliers
numeric_cols = df.select_dtypes(include='number').columns.tolist()

for col in numeric_cols:
    missing_count = df[col].isnull().sum()
    if missing_count > 0:
        median_val = df[col].median()
        df[col].fillna(median_val, inplace=True)
        print(f"  {col}: filled {missing_count} NaNs with median={median_val:.3f}")

# ── Final check: confirm no more missing values ──────────────────────
remaining = df.isnull().sum().sum()
print(f"\nTotal missing values remaining: {remaining}")
print(f"Dataset shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print("✅ Ready for EDA")

# See which columns still have missing values and their types
print("Columns still missing:\n")
for col in df.columns:
    n = df[col].isnull().sum()
    if n > 0:
        print(f"  {col:40s}  missing: {n:>4}   dtype: {df[col].dtype}")

# Force-convert any remaining columns that should be numeric but aren't
suspect_cols = ['hf_discharges', 'hf_readmissions', 'predicted_rate', 'expected_rate']

for col in suspect_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')  # convert to number first

# Now re-run median fill on everything numeric
numeric_cols = df.select_dtypes(include='number').columns
for col in numeric_cols:
    n = df[col].isnull().sum()
    if n > 0:
        df[col].fillna(df[col].median(), inplace=True)
        print(f"Filled {n} missing values in '{col}'")

print(f"\nTotal missing remaining: {df.isnull().sum().sum()}")

# Fill the remaining text/object columns
text_fills = {
    'Facility Name':  'Unknown Hospital',
    'City/Town':      'Unknown City',
    'ownership_cat':  'Unknown',
    'type_cat':       'Unknown',
}

for col, fill_val in text_fills.items():
    if col in df.columns:
        n = df[col].isnull().sum()
        if n > 0:
            df[col].fillna(fill_val, inplace=True)
            print(f"Filled {n} missing in '{col}' → '{fill_val}'")

print(f"\nTotal missing remaining: {df.isnull().sum().sum()}")

df.to_csv('team7_master_dataset.csv', index=False)

from google.colab import files
files.download('team7_master_dataset.csv')

print("📂 Upload: Complications_and_Deaths-Hospital.csv")
uploaded = files.upload()

comp_raw = pd.read_csv(list(uploaded.keys())[0])
comp_raw['Facility ID'] = comp_raw['Facility ID'].astype(str).str.zfill(6)
print(f"Raw rows (long format): {len(comp_raw):,}")
print(f"Unique measures: {comp_raw['Measure ID'].nunique()}")
print(comp_raw['Measure ID'].unique())

# Key measures relevant to Heart Failure
COMP_KEEP = {
    'MORT_30_HF':        'mort_30_hf',        # 30-day HF mortality rate
    'MORT_30_AMI':       'mort_30_ami',        # 30-day AMI mortality
    'MORT_30_PN':        'mort_30_pn',         # 30-day pneumonia mortality
    'PSI_4_SURG_COMP':   'comp_surg',          # Surgical complications
    'COMP_HIP_KNEE':     'comp_hip_knee',      # Hip/knee complications
    'PSI_90_SAFETY':     'comp_psi90_safety',  # Patient safety composite
}

comp_long = comp_raw[
    comp_raw['Measure ID'].isin(COMP_KEEP.keys())
][['Facility ID','Measure ID','Score']].copy()

comp_long['Score'] = pd.to_numeric(
    comp_long['Score'].replace({'Not Available': np.nan, 'Too Few Cases': np.nan}),
    errors='coerce'
)

# Pivot long → wide
comp = (comp_long
        .pivot_table(index='Facility ID',
                     columns='Measure ID',
                     values='Score',
                     aggfunc='mean')
        .reset_index())
comp.columns.name = None
comp.rename(columns=COMP_KEEP, inplace=True)

print(f"Complications wide: {len(comp):,} hospitals")
print(f"Columns: {[c for c in comp.columns if c != 'Facility ID']}")
comp.head()

print("📂 Upload: FY2021_Value_Based_Incentive_Payment_Amount.csv")
uploaded = files.upload()

vbp_raw = pd.read_csv(list(uploaded.keys())[0])
print(f"Loaded: {len(vbp_raw):,} rows")
print(f"Columns: {vbp_raw.columns.tolist()}")
vbp_raw.head()

# Standardize Facility ID — VBP file may call it 'Provider Number' or 'Facility ID'
id_col_candidates = [c for c in vbp_raw.columns if 'provider' in c.lower() or 'facility' in c.lower()]

if id_col_candidates:
    id_col = id_col_candidates[0]
    vbp_raw[id_col] = vbp_raw[id_col].astype(str).str.zfill(6)
    vbp_raw.rename(columns={id_col: 'Facility ID'}, inplace=True)

    # Keep payment amount and total performance score
    keep = ['Facility ID']
    for col in vbp_raw.columns:
        if any(k in col.lower() for k in ['payment','incentive','performance','score','adjustment']):
            keep.append(col)

    vbp = vbp_raw[keep].copy()

    # Rename to clean column names
    vbp.columns = ['Facility ID'] + [
        'vbp_' + c.lower().replace(' ','_').replace('/','_').replace('(','').replace(')','')[:30]
        for c in vbp.columns[1:]
    ]

    # Convert all to numeric
    for col in vbp.columns[1:]:
        vbp[col] = pd.to_numeric(vbp[col], errors='coerce')

    print(f"VBP dataset: {len(vbp):,} hospitals")
    print(f"Columns: {vbp.columns.tolist()}")
    vbp.head()
elif 'facility id' in [c.lower() for c in vbp_raw.columns]: # Added this check in case of exact match
    vbp_raw.rename(columns={'Facility ID': 'Facility ID'}, inplace=True)
    vbp_raw['Facility ID'] = vbp_raw['Facility ID'].astype(str).str.zfill(6)
    id_col = 'Facility ID'

    keep = ['Facility ID']
    for col in vbp_raw.columns:
        if any(k in col.lower() for k in ['payment','incentive','performance','score','adjustment']):
            keep.append(col)

    vbp = vbp_raw[keep].copy()

    vbp.columns = ['Facility ID'] + [
        'vbp_' + c.lower().replace(' ','_').replace('/','_').replace('(','').replace(')','')[:30]
        for c in vbp.columns[1:]
    ]

    for col in vbp.columns[1:]:
        vbp[col] = pd.to_numeric(vbp[col], errors='coerce')

    print(f"VBP dataset: {len(vbp):,} hospitals")
    print(f"Columns: {vbp.columns.tolist()}")
    vbp.head()
else:
    print("Warning: The VBP raw data does not contain 'Facility ID' or 'Provider Number' columns. Skipping VBP data processing.")
    vbp = pd.DataFrame(columns=['Facility ID']) # Create an empty DataFrame to avoid errors in subsequent merges

print("Merging all 8 datasets...\n")

df = hf.copy()
print(f"Spine (HF):              {len(df):>6,} rows")

df = df.merge(hosp,   on='Facility ID', how='left')
print(f"+ Hospital Info:         {len(df):>6,} rows")

df = df.merge(hcahps, on='Facility ID', how='left')
print(f"+ HCAHPS:                {len(df):>6,} rows")

df = df.merge(timely, on='Facility ID', how='left')
print(f"+ Timely Care:           {len(df):>6,} rows")

df = df.merge(hac,    on='Facility ID', how='left')
print(f"+ HAC Safety:            {len(df):>6,} rows")

df = df.merge(mspb,   on='Facility ID', how='left')
print(f"+ Medicare Spending:     {len(df):>6,} rows")

df = df.merge(comp,   on='Facility ID', how='left')
print(f"+ Complications/Deaths:  {len(df):>6,} rows")

df = df.merge(vbp,    on='Facility ID', how='left')
print(f"+ Value-Based Purchasing:{len(df):>6,} rows")

print(f"\n✅ Final merged shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
df.head()

from google.colab import files
files.download('team7_master_dataset.csv')

import os
size_mb = os.path.getsize('team7_master_dataset.csv') / (1024 * 1024)
print(f"CSV size: {size_mb:.1f} MB")
